SET NOCOUNT ON

SET IDENTITY_INSERT [dbo].[TipoVehiculos] ON

MERGE INTO [dbo].[TipoVehiculos] AS [Target]
USING (VALUES
  (1,N'CHASIS CON CABINA')
 ,(2,N'PICK-UP')
 ,(3,N'RURAL 5 PUERTAS')
 ,(4,N'TODO TERRENO')
 ,(5,N'TRACTOR C/CABINA DORMITORIO')
 ,(6,N'DESCAPOTABLE')
 ,(7,N'CICLOMOTOR')
 ,(8,N'FURGON')
 ,(9,N'MOTONETA / SCOOTER')
 ,(10,N'MOTOVEHICULO')
 ,(11,N'TRANS.DE PASAJEROS')
 ,(12,N'CHASIS S/CABINA')
 ,(13,N'SEDAN 2 PUERTAS')
 ,(14,N'FURGONETA')
 ,(15,N'RURAL 4/5 PUERTAS')
 ,(16,N'CAMION C/CABINA DORMITORIO')
 ,(17,N'MOTOCICLETA')
 ,(18,N'TRANSPORTE DE PASAJEROS')
 ,(19,N'CUATRICICLO')
 ,(20,N'SIN ESPECIFICACION')
 ,(21,N'PICK-UP CABINA SIMPLE')
 ,(22,N'CAMION')
 ,(23,N'SEDAN 5 PUERTAS')
 ,(24,N'CONVERTIBLE')
 ,(25,N'SEDAN 4 PUERTAS')
 ,(26,N'TRACTOR DE CARRETERA')
 ,(27,N'FAMILIAR')
 ,(28,N'SEDAN 3 PUERTAS')
 ,(29,N'UTILITARIO')
 ,(30,N'PICK-UP CABINA Y MEDIA')
 ,(31,N'RURAL 4 PUERTAS')
 ,(32,N'COUPE')
 ,(33,N'SCOOTER')
 ,(34,N'RURAL 3 PUERTAS')
 ,(35,N'FURGONETA O UTILITARIO')
 ,(36,N'ARENERO')
 ,(37,N'TRICICLO')
 ,(38,N'PICK-UP CABINA DOBLE')
 ,(39,N'CHASIS C/CABINA DORMITORIO')
 ,(40,N'CHASIS C/CABINA')
 ,(41,N'FURGON O UTILITARIO')
 ,(42,N'CHASIS SIN CABINA')
 ,(43,N'PICK-UP CARROZADA')
 ,(44,N'CHASIS CON CABINA')
 ,(45,N'TRACTOR C/CABINA DORMITORIO')
 ,(46,N'CHASIS CON CABINA DORMITORIO')
 ,(47,N'PICK-UP')
 ,(48,N'RURAL 5 PUERTAS')
 ,(49,N'TODO TERRENO')
 ,(50,N'JEEP')
 ,(51,N'DESCAPOTABLE')
 ,(52,N'CICLOMOTOR')
 ,(53,N'Column10')
 ,(54,N'SEDAN 3 PUERTAS CON PORTON')
 ,(55,N'FURGON')
 ,(56,N'MOTONETA / SCOOTER')
 ,(57,N'MOTOVEHICULO')
 ,(58,N'TRANS.DE PASAJEROS')
 ,(59,N'CHASIS S/CABINA')
 ,(60,N'SEDAN 2 PUERTAS')
 ,(61,N'FURGONETA')
 ,(62,N'RURAL 4/5 PUERTAS')
 ,(63,N'DORMITORIO')
 ,(64,N'MOTOCICLETA')
 ,(65,N'PICK-UP CABINA Y MEDIA')
 ,(66,N'CHASIS C/CABINA DORMITORIO')
 ,(67,N'CUATRIC.C/DISP.ENG.')
 ,(68,N'CUATRICICLO')
 ,(69,N'SIN ESPECIFICACION')
 ,(70,N'TRACTOR DE CARRETERA')
 ,(71,N'PICK-UP CABINA SIMPLE')
 ,(72,N'CAMION')
 ,(73,N'TECTOR 240E28 PASO 4815 CHASIS C/CABINA')
 ,(74,N'SEDAN 5 PUERTAS')
 ,(75,N'CONVERTIBLE')
 ,(76,N'SEDAN 4 PUERTAS')
 ,(77,N'MINIBUS')
 ,(78,N'TRACTOR')
 ,(79,N'Desc. Tipo')
 ,(80,N'CARGO 1933 48 CD ST AMT CHASIS C/CABINA')
 ,(81,N'FAMILIAR')
 ,(82,N'FURGONETA O UTILITARIO')
 ,(83,N'SEDAN 3 PUERTAS')
 ,(84,N'UTILITARIO')
 ,(85,N'MINIBUS (O MICROOMNIBUS)')
 ,(86,N'TRACTOR CON CABINA DORMITORIO')
 ,(87,N'CAMION C/CABINA DORMITORIO')
 ,(88,N'PICK UP')
 ,(89,N'RURAL 4 PUERTAS')
 ,(90,N'CARGO 1729 6X2 53 CD MT CHASIS C/CABINA')
 ,(91,N'COUPE')
 ,(92,N'SCOOTER')
 ,(93,N'RURAL 3 PUERTAS')
 ,(94,N'CHASIS CON CABINA DOBLE')
 ,(95,N'CAMION GRUA')
 ,(96,N'ARENERO')
 ,(97,N'TRICICLO DE CARGA')
 ,(98,N'TRICICLO')
 ,(99,N'PICK-UP CABINA DOBLE')
 ,(100,N'TRANSPORTE DE PASAJEROS')
 ,(101,N'CHASIS C/CABINA')
 ,(102,N'FURGON O UTILITARIO')
 ,(103,N'CHASIS SIN CABINA')
 ,(104,N'PICK-UP CARROZADA')
 ,(105,N'MIDIBUS')
 ,(106,N'OMNIBUS')
) AS [Source] ([TipoVehiculoId],[Descripcion])
ON ([Target].[TipoVehiculoId] = [Source].[TipoVehiculoId])
WHEN MATCHED AND (
	NULLIF([Source].[Descripcion], [Target].[Descripcion]) IS NOT NULL OR NULLIF([Target].[Descripcion], [Source].[Descripcion]) IS NOT NULL) THEN
 UPDATE SET
  [Target].[Descripcion] = [Source].[Descripcion]
WHEN NOT MATCHED BY TARGET THEN
 INSERT([TipoVehiculoId],[Descripcion])
 VALUES([Source].[TipoVehiculoId],[Source].[Descripcion])
WHEN NOT MATCHED BY SOURCE THEN 
 DELETE;

DECLARE @mergeError int
 , @mergeCount int
SELECT @mergeError = @@ERROR, @mergeCount = @@ROWCOUNT
IF @mergeError != 0
 BEGIN
 PRINT 'ERROR OCCURRED IN MERGE FOR [dbo].[TipoVehiculos]. Rows affected: ' + CAST(@mergeCount AS VARCHAR(100)); -- SQL should always return zero rows affected
 END
ELSE
 BEGIN
 PRINT '[dbo].[TipoVehiculos] rows affected by MERGE: ' + CAST(@mergeCount AS VARCHAR(100));
 END
GO



SET IDENTITY_INSERT [dbo].[TipoVehiculos] OFF
SET NOCOUNT OFF
GO