export const REQUEST_ESTADOCIVIL = 'REQUEST_ESTADOCIVIL'
export const RECEIVE_ESTADOCIVIL = 'RECEIVE_ESTADOCIVIL'

export const GET_ESTADOCIVIL_SUCESS = 'GET_ESTADOCIVIL_SUCESS'
export const GET_ESTADOCIVIL_FAILURE = 'GET_ESTADOCIVIL_FAILURE'

export const ADD_ESTADOCIVIL_SUCESS = 'ADD_ESTADOCIVIL_SUCESS'
export const ADD_ESTADOCIVIL_FAILURE = 'ADD_ESTADOCIVIL_FAILURE'

export const UPDATE_ESTADOCIVIL_SUCESS = 'UPDATE_ESTADOCIVIL_SUCESS'
export const UPDATE_ESTADOCIVIL_FAILURE = 'UPDATE_ESTADOCIVIL_FAILURE'

export const DELETE_ESTADOCIVIL_SUCESS = 'DELETE_ESTADOCIVIL_SUCESS'
export const DELETE_ESTADOCIVIL_FAILURE = 'DELETE_ESTADOCIVIL_FAILURE'

