export const REQUEST_MARCA = 'REQUEST_MARCA'
export const RECEIVE_MARCA = 'RECEIVE_MARCA'

export const GET_MARCA_SUCESS = 'GET_MARCA_SUCESS'
export const GET_MARCA_FAILURE = 'GET_MARCA_FAILURE'

export const ADD_MARCA_SUCESS = 'ADD_MARCA_SUCESS'
export const ADD_MARCA_FAILURE = 'ADD_MARCA_FAILURE'

export const UPDATE_MARCA_SUCESS = 'UPDATE_MARCA_SUCESS'
export const UPDATE_MARCA_FAILURE = 'UPDATE_MARCA_FAILURE'

export const DELETE_MARCA_SUCESS = 'DELETE_MARCA_SUCESS'
export const DELETE_MARCA_FAILURE = 'DELETE_MARCA_FAILURE'

