export const REQUEST_MODELO = 'REQUEST_MODELO'
export const RECEIVE_MODELO = 'RECEIVE_MODELO'

export const GET_MODELO_SUCESS = 'GET_MODELO_SUCESS'
export const GET_MODELO_FAILURE = 'GET_MODELO_FAILURE'

export const ADD_MODELO_SUCESS = 'ADD_MODELO_SUCESS'
export const ADD_MODELO_FAILURE = 'ADD_MODELO_FAILURE'

export const UPDATE_MODELO_SUCESS = 'UPDATE_MODELO_SUCESS'
export const UPDATE_MODELO_FAILURE = 'UPDATE_MODELO_FAILURE'

export const DELETE_MODELO_SUCESS = 'DELETE_MODELO_SUCESS'
export const DELETE_MODELO_FAILURE = 'DELETE_MODELO_FAILURE'

