export const REQUEST_TRANSACCION = 'REQUEST_TRANSACCION'
export const RECEIVE_TRANSACCION = 'RECEIVE_TRANSACCION'

export const REQUEST_TRANSACCION_BY_VEHICULO = 'REQUEST_TRANSACCION_BY_VEHICULO'
export const RECEIVE_TRANSACCION_BY_VEHICULO = 'RECEIVE_TRANSACCION_BY_VEHICULO'

export const GET_TRANSACCION_SUCESS = 'GET_TRANSACCION_SUCESS'

export const ADD_TRANSACCION_SUCESS = 'ADD_TRANSACCION_SUCESS'

export const UPDATE_TRANSACCION_SUCESS = 'UPDATE_TRANSACCION_SUCESS'

export const DELETE_TRANSACCION_SUCESS = 'DELETE_TRANSACCION_SUCESS'

