export const REQUEST_VEHICULO = 'REQUEST_VEHICULO'
export const RECEIVE_VEHICULO = 'RECEIVE_VEHICULO'

export const GET_VEHICULO_SUCESS = 'GET_VEHICULO_SUCESS'

export const ADD_VEHICULO_SUCESS = 'ADD_VEHICULO_SUCESS'

export const UPDATE_VEHICULO_SUCESS = 'UPDATE_VEHICULO_SUCESS'

export const DELETE_VEHICULO_SUCESS = 'DELETE_VEHICULO_SUCESS'

